### ISSUE TITLE
Doesn't run in chrome

### ISSUE THREAD

**Issue by radiantone** [VisualDataWeb/WebVOWL#153]
I download the zip and open the index.html file in chrome. Errors.
Uncaught DOMException: Failed to read the 'cssRules' property from 'CSSStyleSheet': Cannot access rules
    at n (file:///home/xxx/webvowl/js/webvowl.app.js:5:12205)
    at e.exports (file:///home/xxx/webvowl/js/webvowl.app.js:5:12404)
    at Object.e.exports [as app] (file:///home/xxx/webvowl/js/webvowl.app.js:1:7647)
    at file:///home/xxx/webvowl/index.html:473:33

**Comment by vitalis-wiens** [comment]
Hi, this is related to chromes CORS (firefox works fine), see #151 .

We are currently preparing a new version that fixes this particular issue .

**Comment by vitalis-wiens** [comment]
Fixed, see #151
