### ISSUE TITLE
Unable to start webserver

### ISSUE THREAD

**Issue by wouterbeek** [VisualDataWeb/WebVOWL#155]
```$ npm run-script webserver 

> webvowl@1.1.4 webserver /home/wbeek/triply/WebVOWL
> grunt webserver

Running "clean:deploy" (clean) task
>> 1 path cleaned.

Running "clean:zip" (clean) task
>> 0 paths cleaned.

Running "copy:dependencies" (copy) task
Copied 1 file

Running "copy:static" (copy) task
Copied 2 files

Running "webpack:build-dev" (webpack) task
Version: webpack 1.15.0     
                  Asset       Size  Chunks             Chunk Names
 data/new_ontology.json  560 bytes          [emitted]  
          js/webvowl.js     762 kB       0  [emitted]  webvowl
        css/webvowl.css    5.25 kB       0  [emitted]  webvowl
    css/webvowl.app.css    37.6 kB       1  [emitted]  webvowl.app
      js/webvowl.js.map     930 kB       0  [emitted]  webvowl
    css/webvowl.css.map   92 bytes       0  [emitted]  webvowl
  js/webvowl.app.js.map     413 kB       1  [emitted]  webvowl.app
css/webvowl.app.css.map   96 bytes       1  [emitted]  webvowl.app
      js/webvowl.app.js     353 kB       1  [emitted]  webvowl.app
     data/template.json    2.72 kB          [emitted]  
    data/benchmark.json    23.9 kB          [emitted]  
         data/muto.json    27.6 kB          [emitted]  
     data/ontovibe.json    42.1 kB          [emitted]  
         data/foaf.json    74.7 kB          [emitted]  
         data/sioc.json    87.5 kB          [emitted]  
 data/personasonto.json      96 kB          [emitted]  
data/goodrelations.json     222 kB          [emitted]  
Child extract-text-webpack-plugin:
    
Child extract-text-webpack-plugin:
    

Running "replace:dist" (replace) task
>> 3 replacements in 2 files.

Running "htmlbuild:dev" (htmlbuild) task
>> File deploy/index.html created !

Running "connect:devserver" (connect) task
Started connect web server on http://localhost:8000

Running "watch" task
Waiting...
(node:4385) UnhandledPromiseRejectionWarning: Error: Exited with code 4
    at ChildProcess.<anonymous> (/home/wbeek/triply/WebVOWL/node_modules/opn/index.js:83:13)
    at Object.onceWrapper (events.js:286:20)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:198:13)
    at Pipe._handle.close (net.js:606:12)

(node:4385) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4385) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by vitalis-wiens** [comment]
I tested it with the following versions 
npm -v 6.4.1
node -v v10.15.3

and it works for me.

what versions do you use?

**Comment by wouterbeek** [comment]
```
$ node --version
v10.16.0
$ npm --version
6.9.0
$ grunt --version
grunt-cli v1.3.2
```

I'm on Fedora 30.

**Comment by vitalis-wiens** [comment]
@wouterbeek have you figured it out?

If you have a solution, I think it would be great if you could share it here :)

**Comment by wouterbeek** [comment]
@vitalis-wiens Nope, I'm not proficient in Node/NPM/Grunt, so I'm also waiting for a more qualified person to give the answer.
