### ISSUE TITLE
Build problem

### ISSUE THREAD

**Issue by cuneytyvz** [VisualDataWeb/WebVOWL#57]
Hi,

I fetched the repository and then run sudo npm install, it installed 33 packages then stuck at this line

```
.
.
.
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.30","npm":"1.4.21"})
npm WARN engine is-buffer@1.1.3: wanted: {"node":">=0.12"} (current: {"node":"0.10.30","npm":"1.4.21"})
-
> fsevents@1.0.12 install /Users/cnytync/Hacking/tools/WebVOWL/node_modules/karma/node_modules/chokidar/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

[fsevents] Success: "/Users/cnytync/Hacking/tools/WebVOWL/node_modules/karma/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v11-darwin-x64/fse.node" is installed via remote

> fsevents@1.0.12 install /Users/cnytync/Hacking/tools/WebVOWL/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

[fsevents] Success: "/Users/cnytync/Hacking/tools/WebVOWL/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v11-darwin-x64/fse.node" is installed via remote


```
Then I canceled the npm installation and tried 'grunt' command then i got this error : 

```
module.js:340
    throw err;
          ^
Error: Cannot find module 'inherits'
  at Function.Module._resolveFilename (module.js:338:15)
  at Function.Module._load (module.js:280:25)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/Users/cnytync/Hacking/tools/WebVOWL/node_modules/grunt/node_modules/glob/glob.js:46:16)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (/Users/cnytync/Hacking/tools/WebVOWL/node_modules/grunt/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/Users/cnytync/Hacking/tools/WebVOWL/node_modules/grunt/lib/grunt/file.js:13:13)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (/Users/cnytync/Hacking/tools/WebVOWL/node_modules/grunt/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at gRequire (/Users/cnytync/Hacking/tools/WebVOWL/node_modules/grunt/lib/grunt.js:14:24)
  at Object.<anonymous> (/Users/cnytync/Hacking/tools/WebVOWL/node_modules/grunt/lib/grunt.js:28:1)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/usr/local/lib/node_modules/grunt-cli/bin/grunt:45:1)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Function.Module.runMain (module.js:497:10)
  at startup (node.js:119:16)
  at node.js:906:3
```

**Comment by cuneytyvz** [comment]
Fixed after uninstalling and reinstalling nom
